export enum ConstraintType{
    LEVEL_CONSTRAINT,
    MULTI_VALUES_CONSTRAINT,
    TIME_CONSTRAINT,
    VALUE_CONSTRAINT,
    CERTIFICATE_CONSTRAINT,
    CRYPTOGRAPHIC_CONSTRAINT,
    BASIC_SIGNATURE_CONSTRAINT,
    SIGNED_ATTRIBUTES_CONSTRAINT,
    UNSIGNED_ATTRIBUTES_CONSTRAINT,
    TIME_STAMP_CONSTRAINTS
}